### PR TITLE
Prep for Kotlin 2.0.20

### PR DESCRIPTION
**Pull request by ZacSweers**

### CODE REVIEW

**Comment by hfhbd** [comment]
Do you have any snapshot builds with 2.0.20-Beta2 support?

**Comment by ZacSweers** [comment]
No as there are no API changes I've seen. Do you need one?

**Comment by hfhbd** [comment]
I think so, I get this error when using Kotlin 2.0.20-Beta2 (or 1) with a compiler plugin compiled with Kotlin 2.0.0 and using `IrFactory`:
```
java.lang.NoClassDefFoundError: org/jetbrains/kotlin/ir/declarations/IrFactory$DefaultImpls
```

**Comment by ZacSweers** [comment]
This library doesn't implement any IR plugins of its own. That's an issue you have to fix on your side

**Comment by hfhbd** [comment]
Yes I know, but there was an incompatible change (change of IrFactory from interface to open class) in the kotlin compiler so using the IrFactory compiled with 2.0.20-Beta2 throws a NoClassDefFoundError when using compiler testing using 2.0.0 because the default parameter class generated for the interface does not exist anymore.

**Comment by ZacSweers** [comment]
That class isn't implemented in this library, I'm really not following. Please be more specific (full trace pointing to where this library is responsible for providing that API). It sounds like you should just be forcing a newer version of the underlying compiler dependency.

**Comment by hfhbd** [comment]
> It sounds like you should just be forcing a newer version of the underlying compiler dependency.

I didn't know this is possible, but yes I agree, sounds like the solution I am missing. Do you have any sample to override the Kotlin compiler dependency?

**Comment by ZacSweers** [comment]
It's a gradle dependency like any other. You can see its declaration here: https://github.com/ZacSweers/kotlin-compile-testing/blob/main/core/build.gradle.kts#L34

**Comment by hfhbd** [comment]
Thanks for your help, it does work, nice!
