### ISSUE TITLE
NoSuchMethodError during KSP ResolverImpl init on Kotlin 2.1.20

### ISSUE THREAD

**Issue by kevinguitar** [ZacSweers/kotlin-compile-testing#332]
Hello 👋 
I'm getting a `NoSuchMethodError` after upgrading to Kotlin 2.1.20, here are the settings we're using:
- kotlin 2.1.20
- ksp 2.1.20-2.0.1
- kctfork:ksp 0.7.1

Minumum reproducible code:

```kotlin
import com.google.auto.service.AutoService
import com.google.common.truth.Truth.assertThat
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.KSAnnotated
import com.tschuchort.compiletesting.KotlinCompilation
import com.tschuchort.compiletesting.KotlinCompilation.ExitCode
import com.tschuchort.compiletesting.configureKsp
import org.jetbrains.kotlin.compiler.plugin.ExperimentalCompilerApi
import org.junit.Test

class DummyCodeGenerator : SymbolProcessor {

    @AutoService(SymbolProcessorProvider::class)
    class Provider : SymbolProcessorProvider {
        override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor {
            return DummyCodeGenerator()
        }
    }

    override fun process(resolver: Resolver): List<KSAnnotated> = emptyList()
}

class DemoTest {

    @Test
    fun `missing LanguageVersionSettings test`() {
        val compilation = KotlinCompilation().apply {
            // Set to 1.9 because we haven't migrated to K2 ksp yet
            languageVersion = "1.9"
            configureKsp(useKsp2 = false) {
                symbolProcessorProviders += DummyCodeGenerator.Provider()
            }
        }
        val result = compilation.compile()
        assertThat(result.exitCode).isEqualTo(ExitCode.OK)
    }
}
```

This is the error I got:
```
e: java.lang.NoSuchMethodError: 'org.jetbrains.kotlin.config.LanguageVersionSettings org.jetbrains.kotlin.codegen.state.KotlinTypeMapper$Companion.getLANGUAGE_VERSION_SETTINGS_DEFAULT()'
	at com.google.devtools.ksp.processing.impl.ResolverImpl.<init>(ResolverImpl.kt:152)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:231)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:112)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:75)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze$lambda$7(KotlinToJVMBytecodeCompiler.kt:326)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:112)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:317)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.runFrontendAndGenerateIrUsingClassicFrontend(KotlinToJVMBytecodeCompiler.kt:154)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:75)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:167)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:36)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:113)
	at org.jetbrains.kotlin.cli.common.CLICompiler.exec(CLICompiler.kt:337)
	at com.tschuchort.compiletesting.AbstractKotlinCompilation.compileKotlin(AbstractKotlinCompilation.kt:274)
	at com.tschuchort.compiletesting.KotlinCompilation.compileJvmKotlin(KotlinCompilation.kt:415)
	at com.tschuchort.compiletesting.KotlinCompilation.compile(KotlinCompilation.kt:602)
	at com.bandlab.anvil.rest.api.impl.DemoTest.missing LanguageVersionSettings test(RestApiServiceCodeGeneratorTest.kt:44)
```

**Comment by tabilzad** [comment]
Getting a similar exception after upgrading to 2.1.20 likely due to https://youtrack.jetbrains.com/issue/KT-72075
```
java.lang.NoSuchMethodError: 'org.jetbrains.kotlin.fir.types.ConeClassLikeType org.jetbrains.kotlin.fir.resolve.ScopeUtilsKt.defaultType(org.jetbrains.kotlin.fir.declarations.FirClassLikeDeclaration)'
```

**Comment by ZacSweers** [comment]
See #340

**Comment by kevinguitar** [comment]
Ah I didn't share the full trace, updated the track and details. Meanwhile, trying the 0.7.1 version you just published

**Comment by jimirocks** [comment]
Having the same issue, need upgrade to kotlin 2.1.20 at least - wanna try to help next week hopefully

**Comment by ZacSweers** [comment]
0.8.0 is now on 2.2.0, 2.1.0 isn't supported anymore
